# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbffdaa63d2bfe73dd89e1d2531dfc191531ca73cde63837df517e83c0dd50ac3ec21eb46c15837ea594c0c6cf80f26ecc9fed7d46d9f92776f5e53a48e66361

test:
  secret_key_base: 34dd78cfb789db6e13c6eb2e467601e16fd7686d9d7ec686e32afc87aa028ad702099e320c14106e8f999b009aced2e1375ed1247eb2b3e0aa6f812e7b72dd9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
